// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://esludtfcnmgjzmvbofdv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzbHVkdGZjbm1nanptdmJvZmR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NjU5OTQsImV4cCI6MjA2ODQ0MTk5NH0.8rVBggpGCseWHfX2AETSeSW2Q6JENJDA4HHCP6koVEA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});