// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Read Supabase config from runtime meta tags to avoid hardcoding credentials
const getMeta = (name: string): string | null => {
  const el = document.querySelector(`meta[name="${name}"]`) as HTMLMetaElement | null;
  return el?.content?.trim() || null;
};

const SUPABASE_URL = getMeta('x-supabase-url') || '';
const SUPABASE_PUBLISHABLE_KEY = getMeta('x-supabase-anon-key') || '';

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  // eslint-disable-next-line no-console
  console.error(
    'Missing Supabase configuration. Please set <meta name="x-supabase-url"> and <meta name="x-supabase-anon-key"> in index.html.'
  );
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});